PATH=~/bin:~/code/go/bin:$PATH:/Library/Developer/CommandLineTools/usr/bin

export GOPATH=~/code/go/

bind 'set mark-symlinked-directories on'

# History Defaults Suck
shopt -s histappend
HISTFILESIZE=1000000
HISTSIZE=1000000
HISTCONTROL=ignoreboth
HISTIGNORE='ls:bg:fg:history'
HISTTIMEFORMAT='%F %T '
shopt -s cmdhist
PROMPT_COMMAND="history -a;$PROMPT_COMMAND"

eval "$(pyenv init -)"
eval "$(rbenv init -)"

# added by Anaconda3 4.4.0 installer
#export PATH="/Users/macrael/anaconda/bin:$PATH"

# NVM
export NVM_DIR="$HOME/.nvm"
. "/usr/local/opt/nvm/nvm.sh"

