execute pathogen#infect()

syntax enable
set background=dark
colorscheme solarized
if has("gui_running")
    set guifont=Monaco:h14
endif "guirunning

let mapleader=","
set cmdheight=2 " This is on trial

:set wrap linebreak nolist

" clear hilighting
nnoremap <leader>/ :noh<CR>

" re-source vimrc
map <leader>v :so ~/.vimrc<CR>

" hilight everything
set hlsearch

" All together now
let ctrlp_cmd = 'CtrlPMixed'

" Spaces
set tabstop=8 softtabstop=0 expandtab shiftwidth=4 smarttab

autocmd FileType javascript setlocal shiftwidth=2 tabstop=2
autocmd FileType javascript.jsx setlocal shiftwidth=2 tabstop=2

set hidden

" Search for evereything selected in visual mode correctly
vnoremap * y/<C-R>"<CR>
